items:
  - DIAMOND,3
  - IRON_ORE,1
  - IRON_BLOCK,2
  - IRON_AXE,1
  - IRON_PICKAXE,1
  - DIAMOND_PICKAXE,3
  - DIAMOND_BLOCK,3
  - GOLD_INGOT,2
  - GOLD_AXE,2
  - GOLD_BLOCK,2
  - DIRT,1
  - GRASS_BLOCK,1
  - NETHERITE_BLOCK,3
  - REDSTONE_BLOCK,2
  - WHITE_WOOL,1
  - RED_WOOL,2
  - BLUE_WOOL,2
  - GREEN_WOOL,3
